<?php

namespace App\Filament\Resources\ExcelSetingResource\Pages;

use App\Filament\Resources\ExcelSetingResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateExcelSeting extends CreateRecord
{
    protected static string $resource = ExcelSetingResource::class;
    protected function getRedirectUrl(): string
    {
        return self::getResource()::getUrl('index'); // TODO: Change the autogenerated stub
    }
}

