<?php

namespace App\Filament\Resources\CompanyTajmeehyResource\Pages;

use App\Filament\Resources\CompanyTajmeehyResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;

class CreateCompanyTajmeehy extends CreateRecord
{
    protected static string $resource = CompanyTajmeehyResource::class;
    protected function getRedirectUrl(): string
    {
        return self::getResource()::getUrl('index'); // TODO: Change the autogenerated stub
    }
}
