<?php

namespace App\Filament\Resources\Masrofat\Masrofats;

use App\Filament\Resources\Masrofat\Masrofats\Pages\ManageMasrofats;

use App\Models\masr\MasCenters;
use App\Models\masr\Masrofat;
use App\Models\masr\MasTypeDetails;
use App\Models\masr\MasTypes;
use BackedEnum;
use Carbon\Carbon;
use Filament\Actions\Action;
use Filament\Actions\BulkActionGroup;
use Filament\Actions\DeleteAction;
use Filament\Actions\DeleteBulkAction;
use Filament\Actions\EditAction;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Resources\Resource;
use Filament\Schemas\Components\Utilities\Get;
use Filament\Schemas\Schema;
use Filament\Support\Icons\Heroicon;
use Filament\Tables\Columns\Summarizers\Sum;
use Filament\Tables\Columns\TextColumn;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Filters\SelectFilter;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Support\Collection;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Response;

class MasrofatResource extends Resource
{
    protected static ?string $model = Masrofat::class;

    protected static string|BackedEnum|null $navigationIcon = Heroicon::OutlinedRectangleStack;

protected static ?string $navigationLabel='المصروفات';
   public static function shouldRegisterNavigation(array $parameters = []): bool
   {
       return Auth::user()->can('ادخال مصروفات'); // TODO: Change the autogenerated stub
   }
    public static function form(Schema $schema): Schema
    {
        return $schema
            ->components([
                Select::make('MasType')
                 ->options(MasTypes::all()->pluck('MasTypeName', 'MasTypeNo'))
                 ->searchable()
                 ->preload()
                    ->required()
                 ->live()
                 ->label('نوع المصروفات'),
                Select::make('MasTypeDetail')
                    ->options(fn (Get $get): Collection => MasTypeDetails::query()
                        ->where('MasType', $get('MasType'))
                        ->pluck('DetailName', 'DetailNo'))
                    ->searchable()
                    ->required()
                    ->preload()
                    ->label('التفاصيل'),
                Select::make('MasCenter')
                    ->options(MasCenters::all()->pluck('CenterName', 'CenterNo'))
                    ->searchable()
                    ->preload()
                    ->required()
                    ->label('مصروفة علي'),


                TextInput::make('Val')
                 ->label('المبلغ')
                 ->numeric()
                 ->required(),
                DatePicker::make('MasDate')
                 ->label('التاريخ')
                 ->required(),
                TextInput::make('Notes')
                 ->label('ملاحظات')


            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->pluralModelLabel('الصفحات')
            ->defaultSort('MasNo','desc')
            ->columns([
                TextColumn::make('MasNo')
                 ->label('الرقم الألي'),
                TextColumn::make('MasTypeTable.MasTypeName')
                 ->label('البيان')
                 ->searchable()
                 ->sortable(),
                TextColumn::make('MasTypeDetailTable.DetailName')
                    ->label('تفاصيل المصروفات')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('MasCenterTable.CenterName')
                    ->label('جهة الصرف')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('MasDate')
                    ->label('التاريخ')
                    ->sortable(),
                TextColumn::make('Val')
                    ->numeric('2','.',',')
                    ->summarize(Sum::make()
                        ->label('')
                        ->numeric('2','.',',')
                    )
                    ->label('المبلغ'),
                TextColumn::make('Notes')
                    ->label('ملاحظات'),
            ])

            ->filters([
                SelectFilter::make('MasType')
                 ->label('البيان')
                 ->relationship('MasTypeTable','MasTypeName')
                 ->searchable()
                 ->preload(),
                SelectFilter::make('MasTypeDetail')
                    ->label('التفاصيل')
                    ->relationship('MasTypeDetailTable','DetailName')
                    ->searchable()
                    ->preload(),
                SelectFilter::make('MasCenter')
                    ->label('مصروفة علي')
                    ->relationship('MasCenterTable','CenterName')
                    ->searchable()
                    ->preload(),
                Filter::make('MasDate')
                    ->schema([
                        DatePicker::make('Date1')
                            ->label('من تاريخ'),
                        DatePicker::make('Date2')
                            ->label('إلي تاريخ'),
                    ])
                    ->columns(2)
                    ->indicateUsing(function (array $data): ?string {
                        if (! $data['Date1'] && ! $data['Date2']) { return null;   }
                        if ( $data['Date1'] && !$data['Date2'])
                            return 'اعتبارا من تاريخ  ' . Carbon::parse($data['Date1'])->toFormattedDateString();
                        if ( !$data['Date1'] && $data['Date2'])
                            return 'حتي تاريخ  ' . Carbon::parse($data['Date2'])->toFormattedDateString();
                        if ( $data['Date1'] && $data['Date2'])
                            return 'ادخلت في الفترة من  ' . Carbon::parse($data['Date1'])->toFormattedDateString()
                                .' إلي '. Carbon::parse($data['Date1'])->toFormattedDateString();

                    })
                    ->query(function (Builder $query, array $data): Builder {
                        return $query
                            ->when(
                                $data['Date1'],
                                fn (Builder $query): Builder => $query->whereDate('MasDate', '>=', $data['Date1']),
                            )
                            ->when(
                                $data['Date2'],
                                fn (Builder $query): Builder => $query->whereDate('MasDate', '<=', $data['Date2']),
                            );
                    })
            ])
            ->recordActions([
                EditAction::make()->iconButton()->modalHeading('تعديل مصروفات'),
                DeleteAction::make()
                    ->iconButton()
                    ->modalHeading('حذف هذه المصروفات'),
            ])
            ->toolbarActions([
                BulkActionGroup::make([
                    DeleteBulkAction::make(),
                ]),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => ManageMasrofats::route('/'),
        ];
    }
}
