<?php

namespace App\Filament\Resources\UserResource\Pages;

use App\Filament\Resources\UserResource;
use Filament\Actions;
use Filament\Resources\Pages\CreateRecord;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\DB;

class CreateUser extends CreateRecord
{
    protected static string $resource = UserResource::class;
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $empno=DB::connection(Auth()->user()->company)->table('pass')->max('EMP_NO')+1;
        DB::connection(Auth()->user()->company)->table('pass')->insert([
            'EMP_NO'=>$empno,
            'EMP_NAME'=>$data['name'],
            'pass_no'=>$data['password'],
            'pass_type'=>3,
            'place'=>0,
        ]);
        $data['company']=Auth::user()->company;
        $data['empno']=$empno;
        $data['username']=$data['name'];
        $data['IsAdmin']=0;

        return parent::mutateFormDataBeforeCreate($data); // TODO: Change the autogenerated stub
    }
}
