<?php

namespace App\Filament\Pages;

use App\Models\masr\MasCenters;
use App\Models\stores\halls_names;
use App\Models\stores\stores_names;
use Filament\Actions\Action;
use Filament\Forms\Components\Radio;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Contracts\HasForms;
use Filament\Notifications\Notification;
use Filament\Pages\Page;
use Filament\Schemas\Components\Grid;
use Filament\Schemas\Components\Section;
use Filament\Schemas\Concerns\InteractsWithSchemas;
use Filament\Schemas\Contracts\HasSchemas;
use Filament\Schemas\Schema;
use Illuminate\Support\Facades\Auth;
use UnitEnum;

class InpPlace extends Page implements HasSchemas
{
    use InteractsWithSchemas;
    protected string $view = 'filament.pages.inp-place';

    protected static string | UnitEnum | null $navigationGroup='Setting';
    public static function shouldRegisterNavigation(): bool
    {
        return Auth::user()->id==1; // TODO: Change the autogenerated stub
    }

    public $placeType;
    public $name;

    public function mount(): void
    {
        $this->form->fill(['placeType'=>2,]);
    }

    public function form(Schema $schema): Schema {
        return $schema

            ->components([
                Grid::make()
                  ->schema([
                    Section::make()
                        ->schema([
                            Radio::make('placeType')
                                ->afterStateUpdated(fn ($state) => $this->placeType=$state)
                                ->options([
                                    1=>'store',
                                    2=>'hall',
                                ]),
                            TextInput::make('name')->afterStateUpdated(fn($state)=>$this->name=$state)->required(),
                            Action::make('save')
                             ->action(function (){
                                 if ($this->name){
                                     if ($this->placeType == 1){
                                         if (stores_names::where('st_name', $this->name)->exists()) {
                                             Notification::make()
                                                 ->title('the store is stored pre-registered')
                                                 ->send();
                                             return;
                                         }
                                         $CenterWho=2;
                                         $st_no=stores_names::max('st_no')+1;
                                         stores_names::insert(['st_no'=>$st_no,'st_name'=>$this->name]);
                                         MasCenters::insert([
                                             'CenterNo'=>MasCenters::max('CenterNo')+1,
                                             'CenterName'=>$this->name,
                                             'CenterWho'=>$CenterWho,
                                             'WhoId'=>$st_no,
                                             ]);
                                     }
                                     if ($this->placeType == 2){
                                         if (halls_names::where('hall_name', $this->name)->exists()) {
                                             Notification::make()
                                                 ->title('the hall is stored pre-registered')
                                                 ->send();
                                             return;
                                         }
                                         $CenterWho=1;
                                         $hall_no=halls_names::max('hall_no')+1;
                                         halls_names::insert(['hall_no'=>$hall_no,'hall_name'=>$this->name]);
                                         MasCenters::insert([
                                             'CenterNo'=>MasCenters::max('CenterNo')+1,
                                             'CenterName'=>$this->name,
                                             'CenterWho'=>$CenterWho,
                                             'WhoId'=>$hall_no,
                                         ]);
                                     }
                                     Notification::make()
                                         ->title('تم تخزين البيانات بنجاح')
                                         ->success()
                                         ->send();
                                     $this->name='';
                                     $this->form->fill(['placeType'=>$this->placeType,'name'=>$this->name]);




                                 }
                             }),

                        ]),
                ])



            ]);
    }

}
